import { RoutePages } from "../types/route";

const route: RoutePages = {
  complexes: "/complexes",
  advertisement: "/advertisements",
  us: "/us",
  immovables: "/immovables",
  users: "/users",
  registers: "/registers",
  auth: "/auth",
  profile: "/profile",
  holiday: "/holiday",
  registerComplex: "/registers/complex",
  termsConditions: "/terms-conditions",
  summaryInmov: "/summary-immovables",
  myprofile: "/my-profile",
  mychats: "/my-chats",
  mysocial: "/my-social",
  mynews: "/my-news",
  news: "/my-news/news",
  myadd: "/my-add",
  add: "/my-add/add",
  mywallet: "/my-wallet",
  myuser: "/my-new-user",
  user: "/my-new-user/new-user",
  myworker: "/my-new-workers",
  worker: "/my-new-workers/new-worw",
  myexpiration: "/my-expiration",
  myactivity: "/my-activity",
  activity: "/my-activity/activity",
  myholliday: "/my-holliday",
  vacations: "/my-holliday/vacation",
  mynewadd: "/my-new-add",
  mynewimmovable: "/my-new-immovable",
  immovable: "/my-new-immovable/new-immovable",
  myforo: "/my-foro",
  foro: "/my-foro/foro",
  mycitofonia: "/my-citofonia",
  citofonia: "/my-citofonia/citofonia",
  myvip: "/my-vip",
  mycertification: "/my-certification",
  certification: "/my-certification/certification",
  ensemble: "/ensemble",
  mypqr: "/my-pqr",
  pqr: "/my-pqr/pqr",
  myAllPqr: "/my-all-pqr",
  mysubuser: "/my-subuser",
  mydocuemnts: "/my-documents",
  payComplexes: "/pay-complexes",
  myforum: "/my-all-foro",
  myAssembly: "/my-assembly",
  myallassembly: "/my-all-assembly",
  myAdvertisement: "/my-advertisement",
};

const listPagePublic: string[] = [
  route.complexes,
  route.us,
  route.advertisement,
  route.immovables,
  route.registers,
  route.holiday,
];

const listPagePrivate: string[] = [
  route.myprofile,
  route.mychats,
  route.mysocial,
  route.mywallet,
  route.myuser,
  route.user,
  route.myworker,
  route.worker,
  route.myforo,
  route.foro,
  route.myexpiration,
  route.myholliday,
  route.mycitofonia,
  route.citofonia,
  route.mynews,
  route.news,
  route.myadd,
  route.myadd,
  route.mynewadd,
  route.mynewimmovable,
  route.immovable,
  route.myactivity,
  route.activity,
  route.myvip,
  route.mycertification,
  route.certification,
  route.ensemble,
  route.mypqr,
  route.pqr,
  route.myAllPqr,
  route.mysubuser,
  route.payComplexes,
  route.vacations,
  route.myforum,
  route.myAssembly,
  route.myAdvertisement,
  route.myallassembly,
];

export { listPagePublic, route, listPagePrivate };
