import { RoutePages } from "../types/route";

const route: RoutePages = {
  complexes: "/complexes",
  advertisement: "/advertisements",
  us: "/us",
  immovables: "/immovables",
  users: "/users",
  registers: "/registers",
  auth: "/auth",
  profile: "/profile",
  holiday: "/holiday",
  registerComplex: "/registers/complex",
  termsConditions: "/terms-conditions",
  summaryInmov: "/summary-immovables",
  myprofile: "/my-profile",
  mychats: "/my-chats",
  mysocial: "/my-social",
  mynews: "/my-news",
  news: "/my-news/news",
  myadd: "/my-add",
  mywallet: "/my-wallet",
  myuser: "/my-new-user",
  myexpiration: "/my-expiration",
  myactivity: "/my-activity",
  activity: "/my-activity/activity",
  myholliday: "/my-holliday",
  mynewadd: "/my-new-add",
  mynewimmovable: "/my-new-immovable",
  myforo: "/my-foro",
  mycitofonia: "/my-citofonia",
  citofonia: "/my-citofonia/citofonia",
  myvip: "/my-vip",
  mycertification: "/my-certification",
  ensemble: "/ensemble",
};

const listPagePublic: string[] = [
  route.complexes,
  route.us,
  route.advertisement,
  route.immovables,
  route.registers,
  route.holiday,
];

const listPagePrivate: string[] = [
  route.myprofile,
  route.mychats,
  route.mysocial,
  route.mywallet,
  route.myuser,
  route.myforo,
  route.myexpiration,
  route.myholliday,
  route.mycitofonia,
  route.citofonia,
  route.mynews,
  route.news,
  route.myadd,
  route.mynewadd,
  route.mynewimmovable,
  route.myactivity,
  route.activity,
  route.myvip,
  route.mycertification,
  route.ensemble,
];

export { listPagePublic, route, listPagePrivate };
