export type PlanFeature = {
  text: string;
  tachado?: boolean;
};

export const planFeatures: Record<"basic" | "gold" | "platinum", string[]> = {
  basic: [
    "soporte",
    "social",
    "balance",
    "citofonia",
    "documentos",
    "foro",
    "agente",
    "comunciaciones",
    "cartelera",
    "pazsalvos",
    "pqr",
    "colaboradores",
    "gastos",
    "favoritos",
    "inmuebles",
    "pagos",
    "registroExtermo",
    "registroInterno",
    // division
    // "alianzas",
    // "morosidad",
    // "marketplace",
    // "productos",
    // "red",
    // "asambleas",
    // "locales",
    // "mantenimientos",
    // "familiares",
  ],
  gold: [
    "soporte",
    "social",
    "balance",
    "citofonia",
    "documentos",
    "foro",
    "agente",
    "comunciaciones",
    "cartelera",
    "pazsalvos",
    "pqr",
    "colaboradores",
    "gastos",
    "favoritos",
    "inmuebles",
    "pagos",
    "registroExtermo",
    "registroInterno",
    "asambleas",
    "mantenimientos",
    "familiares",
    // division
    // "alianzas",
    // "morosidad",
    // "marketplace",
    // "productos",
    // "red",
    // "locales",
  ],
  platinum: [
    "soporte",
    "social",
    "balance",
    "citofonia",
    "documentos",
    "foro",
    "agente",
    "comunciaciones",
    "cartelera",
    "pazsalvos",
    "pqr",
    "colaboradores",
    "gastos",
    "favoritos",
    "inmuebles",
    "pagos",
    "registroExtermo",
    "registroInterno",
    // division
    "alianzas",
    "morosidad",
    "marketplace",
    "productos",
    "red",
    "asambleas",
    "locales",
    "mantenimientos",
    "familiares",
  ],
};
