type RoutePages = {
  complexes: string;
  advertisement: string;
  us: string;
  immovables: string;
  users: string;
  registers: string;
  auth: string;
  profile: string;
  holiday: string;
  registerComplex: string;
  termsConditions: string;
  summaryInmov: string;
  myprofile: string;
  mychats: string;
  mysocial: string;
  mynews: string;
  news: string;
  myadd: string;
  mywallet: string;
  myuser: string;
  user: string;
  myexpiration: string;
  myactivity: string;
  activity: string;
  myholliday: string;
  mynewadd: string;
  mynewimmovable: string;
  immovable: string;
  myforo: string;
  foro: string;
  mycitofonia: string;
  citofonia: string;
  myvip: string;
  mycertification: string;
  certification: string;
  ensemble: string;
  mypqr: string;
  pqr: string;
  myAllPqr: string;
  mysubuser: string;
  mydocuemnts: string;
};

export type { RoutePages };
