type RoutePages = {
  complexes: string;
  advertisement: string;
  us: string;
  immovables: string;
  users: string;
  registers: string;
  auth: string;
  profile: string;
  holiday: string;
  registerComplex: string;
  termsConditions: string;
  summaryInmov: string;
  myprofile: string;
  mychats: string;
  mysocial: string;
  mynews: string;
  myadd: string;
  mywallet: string;
  myuser: string;
  myexpiration: string;
  myactivity: string;
  myholliday: string;
  mynewadd: string;
  mynewimmovable: string;
  myforo: string;
  mycitofonia: string;
  myvip: string;
  mycertification: string;
  ensemble: string;
};

export type { RoutePages };
